### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Trqhxrd** [SamJakob/SpiGUI#10]
I am currently writing a Plugin and I would apprechiate, if you could add a github package for me to include in my project. 

I don't work with gradle that much so I don't know, if there is a difference between maven and gradle packages. If there is, please also add a maven-package. 

If that is not possible just close this issue. 

Thank you for taking your time to actually code this!

Kind regards,
Trqhxrd

**Comment by SamJakob** [comment]
Hi, Gradle typically uses Maven packages, however versions of this package are already automatically released to Jitpack for both Gradle, Maven and more.

Instructions are here: https://jitpack.io/#com.samjakob/SpiGUI - simply select the Maven tab.

**Comment by Trqhxrd** [comment]
Okay. Thank you for taking some of your time to read this!
