### ISSUE TITLE
Cant Create Custom Menu Buttons

### ISSUE THREAD

**Issue by SkylarMark** [SamJakob/SpiGUI#11]
I am using your API for a skin setting purpose. But I found myself unable to add a clear skin button along with the autopager next and back button row.

**Comment by iFeliN3x0** [comment]
I can help you with a method that I use (It is not clean at all, but works fine)
1. Create a new `private SGPaginationButtonBuilder` in the SpiGUI class.
2. In the SpiGUI class, create a getter for that new `private SGPaginationButtonBuilder`.
3. Use `myAwesomeMenu.setPaginationButtonBuilder(Main.spiGUI.paginationName());` to set the pagination to that inventory.

**Comment by SamJakob** [comment]
If this is still an issue please see #15.
