### ISSUE TITLE
refreshInventory bug

### ISSUE THREAD

**Issue by iFeliN3x0** [SamJakob/SpiGUI#12]
Hi, to summarize I found a bug on an if statement in the `refreshInventory()` method.
```
// If the new size is different, we'll need to open a new inventory.
if (viewer.getOpenInventory().getTopInventory().getSize() != getPageSize() + (getMaxPage() > 0 ? 9 : 0)) {
    viewer.openInventory(getInventory());
    return;
}
```
My code:
```
SGMenu menu = Main.spiGUI.create("&eInventory", 2);
menu.setAutomaticPaginationEnabled(false);
//Buttons stuff
BukkitScheduler scheduler = Bukkit.getServer().getScheduler();
BukkitTask task = scheduler.runTaskTimer(plugin, new Runnable() {
    @Override
    public void run() {
        menu.clearAllButStickiedSlots();
        //Set buttons stuff again
        menu.refreshInventory(p);
    }
}, 0L, 20L);
menu.setOnClose(inventory -> {
    if (task != null) scheduler.cancelTask(task.getTaskId());
});
```
The problem is that when I use `menu.setAutomaticPaginationEnabled(false);` the previous if statement is called and the scheduler is cancelled because it opens a new inventory and that must not happen because I am not modifying the inventory size after opening the inventory.

**Comment by iKstruuh** [comment]
Is the project abandoned?

**Comment by SamJakob** [comment]
No, it's not I just missed this issue somehow...

---

Ah I see - so the simplest solution in other words would just be a matter of also checking if we've switched between having or not having pagination?

**Comment by PrayRNGesus** [comment]
> Hi, to summarize I found a bug on an if statement in the `refreshInventory()` method.
> 
> ```
> // If the new size is different, we'll need to open a new inventory.
> if (viewer.getOpenInventory().getTopInventory().getSize() != getPageSize() + (getMaxPage() > 0 ? 9 : 0)) {
>     viewer.openInventory(getInventory());
>     return;
> }
> ```
> 
> My code:
> 
> ```
> SGMenu menu = Main.spiGUI.create("&eInventory", 2);
> menu.setAutomaticPaginationEnabled(false);
> //Buttons stuff
> BukkitScheduler scheduler = Bukkit.getServer().getScheduler();
> BukkitTask task = scheduler.runTaskTimer(plugin, new Runnable() {
>     @Override
>     public void run() {
>         menu.clearAllButStickiedSlots();
>         //Set buttons stuff again
>         menu.refreshInventory(p);
>     }
> }, 0L, 20L);
> menu.setOnClose(inventory -> {
>     if (task != null) scheduler.cancelTask(task.getTaskId());
> });
> ```
> 
> The problem is that when I use `menu.setAutomaticPaginationEnabled(false);` the previous if statement is called and the scheduler is cancelled because it opens a new inventory and that must not happen because I am not modifying the inventory size after opening the inventory.

If you just read a little into the code you will find:
`viewer.getOpenInventory().getTopInventory().setContents(this.getInventory().getContents());`

If you just use your brain to replace the variables such as viewer, and this, (this meaning inventory) then you can easily refresh the inventory without using the method.

`player.getOpenInventory().getTopInventory().setContents(myAwesomeMenu.getInventory().getContents());`

**Comment by iKstruuh** [comment]
Currently am using another GUI API, so I don't need this more.
