### ISSUE TITLE
Cannot invoke "java.util.function.Consumer.accept(Object)" because "this.onPageChange" is null when trying to setCurrentPage(1)

### ISSUE THREAD

**Issue by raph559** [SamJakob/SpiGUI#13]
Hello ! 
I don't know how to fix that, maybe I'm just using the function wrong, but I don't think so.
Can someone help me ?

**Comment by SamJakob** [comment]
Can you provide the stack trace and/or the snippet of code from your project where the error occurs?

**Comment by raph559** [comment]
Of course, here it is : 
`configMenu.setButton(0, 10,new SGButton(new ItemBuilder(Material.BONE)
                            .name("Editer les règles")
                            .build())
                            .withListener(event -> {configMenu.setCurrentPage(1);})
                    );`
The error refers to those lines on SGMenu.java :
`public void setCurrentPage (int page) {
        this.currentPage = page;
        this.onPageChange.accept(this);
    }`
