### ISSUE TITLE
No items in close event

### ISSUE THREAD

**Issue by NotroDev** [SamJakob/SpiGUI#16]
Hi.

This code:
```java
addingMenu.setOnClose(event ->
{
    p.getInventory().setContents(event.getInventory().getContents());
});
```
clears my inventory, because getInventory in this event is empty...
Can i somehow get it contents? Or maybe this is just wrong?

**Comment by SamJakob** [comment]
What exactly are you trying to achieve with this?

**Comment by NotroDev** [comment]
> What exactly are you trying to achieve with this?

I have a GUI to put items in, then I want to save them, for example to the ItemStack list

**Comment by NotroDev** [comment]
> PS. And, let me add that I need to configure the page buttons, e.g. replace icons or text, could you add that? I think I can do it manually by editing getInventory(), but it would be appreciated anyway.
![obraz](https://user-images.githubusercontent.com/77281214/170204755-de0dacbd-1cd3-445b-b6b6-6845289d00eb.png)
Ah, okay, sorry!

**Comment by NotroDev** [comment]
Okay, items in close event solved - i've used bukkit event.
But now, i can't make this work:
```java
SGPaginationButtonBuilder builder = Main.instance.spiGUI.getDefaultPaginationButtonBuilder();
builder.buildPaginationButton(SGPaginationButtonType.CURRENT_BUTTON, shopMenu).setIcon(new ItemBuilder(Material.EMERALD).build());

shopMenu.setPaginationButtonBuilder(builder);
```

**Comment by SamJakob** [comment]
> Okay, items in close event solved - i've used bukkit event. But now, i can't make this work:
> 
> ```java
> SGPaginationButtonBuilder builder = Main.instance.spiGUI.getDefaultPaginationButtonBuilder();
> builder.buildPaginationButton(SGPaginationButtonType.CURRENT_BUTTON, shopMenu).setIcon(new ItemBuilder(Material.EMERALD).build());
> 
> shopMenu.setPaginationButtonBuilder(builder);
> ```

`buildPaginationButton` is used internally by SpiGUI to render the pagination buttons, you wouldn't usually call it as you are here.

What you would instead do is create your own SGPaginationButtonBuilder, similar to the way SpiGUI [does it internally](https://github.com/SamJakob/SpiGUI/blob/master/src/main/java/com/samjakob/spigui/SpiGUI.java#L61) and then use `setPaginationButtonBuilder` to use your created pagination button builder instead.

For any buttons you don't want to override (let's say you're only overriding `CURRENT_BUTTON`, you could use the default instead by simply calling `Main.instance.spiGUI.getDefaultPaginationButtonBuilder().buildPaginationButton` _inside_ your own pagination builder (e.g., in the default block of the switch/case).

Overall this API is a bit of a mess and won't even let you add new buttons - you can only override existing ones which is a bit of a silly oversight on my part. I will try and work on fixing it today if I have time.

**Comment by NotroDev** [comment]
Thanks, it's working perfectly.
