### ISSUE TITLE
Remove Page Buttons

### ISSUE THREAD

**Issue by olehrstm** [SamJakob/SpiGUI#18]
Hello, how could I remove the page buttons?

**Comment by SamJakob** [comment]
Hi, what are you trying to achieve? You could just assign items to the first page (if there’s nothing after the first page the buttons won’t be displayed) - or you could add a custom toolbar builder that doesn’t render the buttons

**Comment by SamJakob** [comment]
For future reference, this can be done with `setEnableAutomaticPagination` and specifying false.
