### ISSUE TITLE
Customizing Toolbar (Pagination) buttons

### ISSUE THREAD

**Issue by HeadMonitor** [SamJakob/SpiGUI#23]
Currently as far as I am aware, the Buttons for automatic pages cannot be localised or changed since their lore and names are hardcoded.

Hence a feature I would love to have is the ability to change the lore and names of the buttons.

**Comment by SamJakob** [comment]
You should be able to use the [Toolbar Customization API](https://javadoc.jitpack.io/com/github/samjakob/SpiGUI/v1.3/javadoc/index.html) to generate and totally customize the toolbar buttons with your own lores, names, items and in slots of your choosing, etc.,

It is expected that most developers would use this API to customize the toolbar, however I haven't found the time to fully document it as it's a new API released a few weeks ago.

There is an example of how this is done here:
https://github.com/SamJakob/SpiGUI/blob/ed41ea1a99ede7df4ffffb3720c784d84f6eed51/src/test/java/com/samjakob/spiguitest/SpiGUITest.java#L77-L116
