### ISSUE TITLE
does this plugin have docs?

### ISSUE THREAD

**Issue by astrofox09** [SamJakob/SpiGUI#24]
i cant see wiki! in SpiPaginationGui i can found wiki, but where is the wiki for spigui?

**Comment by SamJakob** [comment]
Sort of... I have the [Quick Start Guide](https://github.com/SamJakob/SpiGUI#quick-start) in the README file, and the test file containing a few examples:
https://github.com/SamJakob/SpiGUI/blob/ed41ea1a99ede7df4ffffb3720c784d84f6eed51/src/test/java/com/samjakob/spiguitest/SpiGUITest.java#L01-L461

It seems I've forgotten to create the Wiki. Was there something specific you needed?

**Comment by astrofox09** [comment]
thanks, i think this is not enough, but i can use it. you need to add wiki
(sorry for my english, im from russia)

**Comment by SamJakob** [comment]
I will work on adding a wiki when I have time, in the mean time, please feel free to open a new issue if you need help with something specific.
