### ISSUE TITLE
Can't use `#create()` method

### ISSUE THREAD

**Issue by DisguisedTurtlee** [SamJakob/SpiGUI#28]
![image](https://github.com/SamJakob/SpiGUI/assets/98926056/cf99028e-9d37-4651-a4c9-cfd55cfc0194)
![image](https://github.com/SamJakob/SpiGUI/assets/98926056/48af08f8-c867-4dd3-af08-ce5046a79511)

**Comment by DisguisedTurtlee** [comment]
just noticed my dumb ass named the class wrong.

**Comment by SamJakob** [comment]
No worries!

To be clear, the issue there appears to be that your main class is named SpiGUI as is, of course, SpiGUI itself and you’ve imported your main class instead of SpiGUI, so I’d recommend renaming your main class to avoid confusion and importing the wrong file.
