### ISSUE TITLE
Please Write Docs!

### ISSUE THREAD

**Issue by ArvidHoppe** [SamJakob/SpiGUI#31]
Please do us a favor and write good documentation.
I wasted literally 3 hours trying to figure out how to make custom Toolbars!
Not everyone knows your thoughts and your concepts!

I really like your effort and the result, don't get me wrong. But I would appreciate a good documentation :)

**Comment by SamJakob** [comment]
Have you checked out the JavaDoc? I think virtually all the methods and even fields should be documented on there:

https://javadoc.jitpack.io/com/github/SamJakob/SpiGUI/1.3.1/javadoc/index.html

Specifically, for your case:

https://javadoc.jitpack.io/com/github/SamJakob/SpiGUI/1.3.1/javadoc/index.html?com/samjakob/spigui/toolbar/SGToolbarBuilder.html

https://javadoc.jitpack.io/com/github/SamJakob/SpiGUI/1.3.1/javadoc/com/samjakob/spigui/menu/SGMenu.html#setToolbarBuilder-com.samjakob.spigui.toolbar.SGToolbarBuilder-

It should be pretty comprehensive. Was there something specific you wanted, e.g., more details in the JavaDoc, a guide or example code?

**Comment by SamJakob** [comment]
Also see here for an example in the demo code:

https://github.com/SamJakob/SpiGUI/blob/edde839de579038fd2f5c1135c2c9cb1fb2a7c46/src/test/java/com/samjakob/spiguitest/SpiGUITest.java#L77

**Comment by ArvidHoppe** [comment]
For me, javadocs are nice if you know what you want to know. But if youre new to a Project or a Library, only a JavaDoc is equali as good as decompiling the jar and read the code itself (im exaggerating here). What I missed was specific Examples and tweeks to your Library in on a centralized, searchable place.

Your JavaDoc is well done, but as an initial Doc, a javadoc isnt the best format i think :)

**Comment by SamJakob** [comment]
Fair enough! I'll write some guides on the GitHub wiki when I have time

**Comment by ArvidHoppe** [comment]
TYSM!
